// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkkcseixxwydechnnbkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpra2NzZWl4eHd5ZGVjaG5uYmtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3ODczNjAsImV4cCI6MjA1NDM2MzM2MH0.p870sB7cAPChHT45M-MS64xm1B4F0timE8s3zydKiJ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);